/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    `maven-publish`
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.0-jre")
}

application {
    // Define the main class for the application.
    //mainClass.set("nutch.App")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.apache.nutch"
            artifactId = "nutch"
            version = "1.18"

            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri("https://repository.apache.org/service/local/staging/deploy/maven2")
        }

    }
}

ant.importBuild("build.xml") {old ->"ant-${old}"}

// the normal classpath
val classpathCollection: FileCollection = layout.files(
    file(project.properties["build.classes"]),
    fileTree(mapOf("dir" to project.properties["build.lib.dir"], "include" to listOf("*.jar")))
)
val classpath: String = classpathCollection.asPath

// ant target "init" renamed to "init-nutch" to avoid gradle naming conflits
tasks.register<Copy>("init-nutch") {
    doLast {
        // making six directories
        mkdir(project.properties["build.dir"])
        mkdir(project.properties["build.classes"])
        mkdir(project.properties["release.dir"])
        mkdir(project.properties["test.build.dir"])
        mkdir(project.properties["test.build.classes"])
        mkdir(project.properties["test.build.lib.dir"])

        // incomplete: changing datetime for all **/*.template in conf.dir
        fileTree(mapOf("dir" to project.properties["conf.dir"], "include" to listOf("**/*.template"))).forEach{ file: File ->
            println(file)
            // FIX: cannot find touch or datetime equivalent
            // file.lastModified() = Date("01/25/1971 2:00 pm")
        }

        // renaming from *.template to * for all files in folders in conf.dir
        fileTree(project.properties["conf.dir"]).matching { include("**/*.template") }.forEach { file: File -> 
            rename { fileName: String ->
                fileName.replace(".template", "")
            }
        }
    }
}

tasks.register<Delete>("clean-default-lib")
{
    description = "clean the project libraries directory (dependencies)"
    delete(project.properties["build.lib.dir"])
}

tasks.register<Delete>("clean-test-lib")
{
    description = "clean the project test libraries directory (dependencies)"
    delete(project.properties["test.build.lib.dir"])
}

tasks.register<Delete>("clean-build")
{
    description = "clean the project built files"
    delete(project.properties["build.dir"])
}

tasks.register<Delete>("clean-dist")
{
    description = "clean the project dist files"
    delete(project.properties["dist.dir"])
}

tasks.register<Delete>("clean-runtime")
{
    description = "clean the project runtime area"
    delete(project.properties["runtime.dir"])
}