/* Generated By:JavaCC: Do not edit this line. PageDescriptionConstants.java */
package org.apache.nutch.quality.dynamic;

public interface PageDescriptionConstants {

  int EOF = 0;
  int KEYWORD = 6;
  int EQUALS = 7;
  int QUOTED_VALUE = 8;
  int UNQUOTED_VALUE = 9;

  int DEFAULT = 0;
  int AFTER_EQUALS = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<KEYWORD>",
    "\"=\"",
    "<QUOTED_VALUE>",
    "<UNQUOTED_VALUE>",
    "\"<search\"",
    "\">\"",
    "\"</search>\"",
    "\"<input\"",
    "\"<interpret\"",
    "\"<\"",
    "\"/>\"",
  };

}
