<?xml version="1.0"?>
<!-- XSLT stylesheet that generates localized versions of the page header. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:template match="header-menu">
    <xsl:comment>This file is automatically generated.  Do not edit!</xsl:comment>
    <table width="635" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td valign="bottom" width="140" rowspan="2">
	  <a href="./"><img src="../img/reiter/logo_nutch.gif" border="0"/></a>
          <img src="../img/reiter/spacer_666666.gif" width="140" height="1"/>
        </td>
      </tr>
      <tr>
        <td width="495" valign="bottom" align="right">
          <table border="0" cellpadding="0" cellspacing="0" width="495">
            <tr>
              <td background="../img/reiter/_bg_reiter.gif" width="400">
                <xsl:text disable-output-escaping="yes">&amp;#160;</xsl:text>
              </td>
<!-- menu -->
              <xsl:for-each select="item">
                <td height="28" valign="bottom" width="10">
                  <xsl:choose>
                    <xsl:when test="position()=1">
                      <img src="../img/reiter/reiter_inactive_le1.gif" border="0"/>
                    </xsl:when>
                    <xsl:otherwise>
                      <img src="../img/reiter/reiter_inactive_le.gif" border="0"/>
                    </xsl:otherwise>
                  </xsl:choose>
                </td>
                <td background="../img/reiter/_bg_reiter_inactive.gif" valign="bottom" nowrap="nowrap">
                  <xsl:variable name="url" select="a/@href"/>
                  <a class="bodytext" href="{$url}">
                    <xsl:value-of select="." disable-output-escaping="yes"/>
                  </a>
                </td>
                <td height="28" valign="bottom" width="10">
                  <img src="../img/reiter/reiter_inactive_ri.gif" border="0"/>
                </td>
              </xsl:for-each>
<!-- menue -->
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </xsl:template>
</xsl:stylesheet>
